project:
  type: website
  output-dir: _site


website:
  title: "AI4Nerds"
  site-url: https://ai4nerds.github.io/blog
  repo-url: https://github.com/ai4nerds/blog
  navbar:
    background: primary
    search: true
    pinned: true
    right:
      - icon: github
        href: https://github.com/ai4nerds/blog

format:
  html:
    theme: 
      - cosmo
      - theme.scss
    css: styles.css
    toc: true
    code-copy: false
    code-tools: false
    highlight-style: github